name: "NodeJS-docker CI"
# Select branch
on:
  push:
    branches: [ "Docker-Pipeline" ]

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }} # Dockerhub username
          password: ${{ vars.DOCKERHUB_TOKEN }} # Dockerhub token

      - name: Build and push docker image
        run: |
          docker build -t rexxx9865/riwajnodeapp:V1.0.0 .
          docker push rexxx9865/riwajnodeapp:V1.0.0

  deploy-to-EC2:
    needs: docker-build
    runs-on: ubuntu-latest
    env:
      SERVER_IP: ${{ vars.SERVER_IP }}
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo -e "Host *\n\tStrictHostKeyChecking no\n" > ~/.ssh/config

      - name: SSH Key Access
        run: |
          echo "${{ secrets.SSH_KEY64 }}" | base64 -d > Riwaj-Key.pem
          chmod 400 Riwaj-Key.pem
          ssh-keygen -R $SERVER_IP || true

      - name: Copy code to EC2
        run: |
          rsync -avz -e "ssh -i Riwaj-Key.pem" ./ ubuntu@$SERVER_IP:/home/ubuntu/nodeapp

      - name: Build & Deploy on EC2
        run: |
          ssh -i Riwaj-Key.pem ubuntu@$SERVER_IP "
            sudo docker pull rexxx9865/riwajnodeapp:V1.0.0 &&
            sudo docker stop mynodeapp || true &&
            sudo docker rm mynodeapp || true &&
            sudo docker run -d --name mynodeapp -p 3000:3000 rexxx9865/riwajnodeapp:V1.0.0 &&
            sudo docker image prune -f
          "
